# Generated by Django 4.2.2 on 2023-09-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=40)),
                ('conteudo', models.CharField(max_length=500)),
                ('datacriacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
