# Generated by Django 4.2.2 on 2023-09-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('ano', models.CharField(max_length=1)),
                ('semester', models.CharField(max_length=10)),
                ('etc', models.CharField(max_length=2)),
            ],
        ),
    ]
